routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TodoController;
use App\Http\Controllers\JourneeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::post('/todos/historique', [TodoController::class, 'historique'])->name('todos.historique');

Route::get('/todos/journee', [JourneeController::class, 'journee'])
		->name('todos.journee');
Route::get('/todos/cloturer', [JourneeController::class, 'cloturer'])->name('todos.cloturer');

Route::get('/todos/achever', [TodoController::class, 'achever'])->name('todos.achever');
Route::get('/todos/done', [TodoController::class, 'done'])->name('todos.done');
Route::get('/todos/undone', [TodoController::class, 'undone'])->name('todos.undone');
Route::get('/todos/createbyme', [TodoController::class, 'createdbyme'])->name('todos.createdbyme');

Route::put('/todos/done/{todo}', [TodoController::class, 'makedone'])->name('todos.makedone');
Route::put('/todos/undone/{todo}', [TodoController::class, 'makeundone'])->name('todos.makeundone');

Route::resource("todos", TodoController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    @notify_css
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav">
                        <a href="{{route('todos.index')}}" class="nav-link">Mes todos</a>
                    </ul>
                     @auth
                    <!-- Historique -->
                    <ul class="navbar-nav">
                        <a href="" class="nav-link" data-toggle="modal" data-target="#formulaire">Historique</a>
                    </ul>
                    <ul class="navbar-nav">
                        <a href="{{route('todos.journee')}}" class="nav-link">Ma journee</a>
                    </ul>
                    @endauth
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Se connecer') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __("S'incrire") }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Deconnexion') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                <div class="justify-content-end my-3">
                    <p class="alert alert-danger" role="alert">S'il vous plait utiliser une connexion internet pour plus de fonctionnalités</p>
                </div>
                <div class="modal fade" id="formulaire">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">Selectionnez une date :</h4>         
                        <button type="button" class="close" data-dismiss="modal">
                          <span>&times;</span>
                        </button>
                      </div>
                      <div class="modal-body row">
                        <form action="{{route('todos.historique')}}" method="POST">
                          <div class="form-group">
                            @csrf
                            <label for="date" class="form-control-label">Choisissez un date</label>
                            <input type="date" class="form-control" name ="date" id="date" required="">
                          </div>
                          <button type="submit" class="btn btn-primary pull-right">Selectionner</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
                @yield('content')
            </div>
        </main>
    </div>
</body>
@notify_js
@notify_render
</html>