routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TodoController;
use App\Http\Controllers\JourneeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::post('/todos/historique', [TodoController::class, 'historique'])->name('todos.historique');

Route::get('/todos/journee', [JourneeController::class, 'journee'])
		->name('todos.journee');
Route::get('/todos/cloturer', [JourneeController::class, 'cloturer'])->name('todos.cloturer');

Route::get('/todos/achever', [TodoController::class, 'achever'])->name('todos.achever');
Route::get('/todos/done', [TodoController::class, 'done'])->name('todos.done');
Route::get('/todos/undone', [TodoController::class, 'undone'])->name('todos.undone');
Route::get('/todos/createbyme', [TodoController::class, 'createdbyme'])->name('todos.createdbyme');

Route::put('/todos/done/{todo}', [TodoController::class, 'makedone'])->name('todos.makedone');
Route::put('/todos/undone/{todo}', [TodoController::class, 'makeundone'])->name('todos.makeundone');

Route::resource("todos", TodoController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

resources/views/pages/_button.blade.php
<div class="row form-inline justify-content-center my-3">
	<a href="{{route('todos.create')}}" class="btn btn-primary mx-2 my-1">Ajouter une todo</a>
	@if(Route::currentRouteName()=='todos.index')
	<a href="" class="nav-link btn btn-dark mx-2 my-1" data-toggle="modal" data-target="#formulaire">Historique</a>
	<a href="{{route('todos.achever')}}" class="btn btn-info mx-2 my-1">Voir les taches achevées</a>
	<a href="{{route('todos.done')}}" class="btn btn-success mx-2 my-1">Voir les taches faites</a>
	<a href="{{route('todos.undone')}}" class="btn btn-warning mx-2 my-1">Voir les taches en cours</a>
	@elseif(Route::currentRouteName()=='todos.achever')
	<a href="" class="nav-link btn btn-dark mx-2 my-1" data-toggle="modal" data-target="#formulaire">Historique</a>
	<a href="{{route('todos.index')}}" class="btn btn-dark">Voir toutes les taches</a>
	<a href="{{route('todos.done')}}" class="btn btn-success mx-2 my-1">Voir les taches faites</a>
	<a href="/todos/undone" class="btn btn-warning mx-2 my-1">Voir les taches en cours</a>
	@elseif(Route::currentRouteName()=='todos.done')
	<a href="" class="nav-link btn btn-dark mx-2 my-1" data-toggle="modal" data-target="#formulaire">Historique</a>
	<a href="{{route('todos.achever')}}" class="btn btn-info mx-2 my-1">Voir les taches achevées</a>
	<a href="{{route('todos.index')}}" class="btn btn-dark">Voir toutes les taches</a>
	<a href="/todos/undone" class="btn btn-warning mx-2 my-1">Voir les taches ouvertes</a>
	@elseif(Route::currentRouteName()=='todos.undone')
	<a href="" class="nav-link btn btn-dark mx-2 my-1" data-toggle="modal" data-target="#formulaire">Historique</a>
	<a href="{{route('todos.achever')}}" class="btn btn-info mx-2 my-1">Voir les taches achevées</a>
	<a href="{{route('todos.index')}}" class="btn btn-dark">Voir toutes les taches</a>
	<a href="{{route('todos.done')}}" class="btn btn-success mx-2 my-1">Voir les taches faites</a>
	@elseif(Route::currentRouteName()=='todos.historique')
	<a href="{{route('todos.index')}}" class="btn btn-dark">Voir toutes les taches</a>
	<a href="{{route('todos.achever')}}" class="btn btn-info mx-2 my-1">Voir les taches achevées</a>
	<a href="/todos/undone" class="btn btn-warning mx-2 my-1">Voir les taches ouvertes</a>
	<a href="{{route('todos.done')}}" class="btn btn-success mx-2 my-1">Voir les taches faites</a>
	@endif
	
</div>

resources/views/pages/_contentPartial.blade.php
@csrf
<div class="form-group {{$errors->has('name') ? 'has-error' : ''}}">
	<label for="name">Nom: </label>
	<input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" placeholder="Enter the name's todo" value="{{old('name') ?: $todo->name}}" aria-describedby="nameHelp">
	<small class="text-muted form-text" id="nameHelp">Enter the name's todo</small>
	{!! $errors->first("name", "<span class='invalid-feedback' role='alert'>:message</span>") !!}
</div>
<div class="form-group">
	<label for="date_fin">Date de fin: </label>
	<input type="date" name="date_fin" id="date_fin" class="form-control @error('date_fin') is-invalid @enderror" placeholder="Enter the name's todo" value="{{old('date_fin') ?: $todo->date_fin}}" aria-describedby="nameHelp">
	{!! $errors->first("date_fin", "<span class='invalid-feedback' role='alert'>:message</span>") !!}
</div>
<div class="form-group">
	<label for="description">Description: </label>
	<textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" aria-describedby="nameHelp">{{old('description') ?: $todo->description}}</textarea>
	{!! $errors->first("description", "<span class='invalid-feedback'>:message</span>") !!}
</div>
<div class="form-group form-check">
	@if(Route::currentRouteName() == 'todos.edit')
	<input  class="form-check-input" type="checkbox" name="done" id="done" {{$todo->done==1 ? "checked" : ""}}>
	<label class="form-check-label" for="done">Fait ?</label>
	@endif
</div>
<button type="submit" class="btn btn-{{$class}}" name="created">{{$buttonName}}</button>
<a href="{{route('todos.index')}}" class="btn btn-default">Annuler</a>

resources/views/pages/create.blade.php
@extends("layouts.app")
@section("content")
	<div class="card">
		<div class="card-titlte card-header bg-success text-white">
			<h4>Creation de la tache</h4>
		</div>
		<div class="card-body">
			<form action="{{route('todos.store')}}" method="POST">
				@include("pages._contentPartial", [
					'class' => 'primary',
					'buttonName' => 'Creer la tache'
				])
			</form>
		</div>
	</div>
@endsection

resources/views/pages/edit.blade.php
@extends("layouts.app")
@section("content")
	

	<div class="card">
		<div class="card-titlte card-header bg-success text-white">
			<h4>Modification de la tache <span class="badge badge-dark">#{{$todo->id}}</span></h4>
		</div>
		<div class="card-body">
			<form action="{{route('todos.update', $todo)}}" method="POST">
				@method("PUT")
				@include("pages._contentPartial", [
					'class' => 'success',
					'buttonName' => 'Modifier la tache'
				])
			</form>
		</div>
	</div>
@endsection

resources/views/pages/index.blade.php
@extends("layouts.app")
@section("content")
{{--BUTTON --}}
@include("pages._button")

<h1>
	@if(Route::currentRouteName()=='todos.index')
	{{"Toutes les taches "}}
	@elseif(Route::currentRouteName()=='todos.achever')
	{{"Les taches achevées "}}
	@elseif(Route::currentRouteName()=='todos.done')
	{{"Les taches faites "}}
	@elseif(Route::currentRouteName()=='todos.undone')
	{{"Les taches en cours "}}
	@elseif(Route::currentRouteName()=='todos.historique')
	{{"Etat de la journee du "}}
	{{$debut}}
	@endif
	({{$todos->total()}})
</h1>

@foreach($todos as $todo)
	@include("pages.todos.info")
@endforeach

{{$todos->links("vendor.pagination.bootstrap-4")}}
@endsection

resources/views/pages/journee.blade.php
@extends("layouts.app")
@section("content")
{{--BUTTON --}}
@include("pages._button")

<div class="row form-inline justify-content-center my-3">
	<h1 class="mx-2 my-1">
		Aujourd'hui
		({{$todos->total()}})
	</h1>
	<a href="{{route('todos.cloturer')}}" class="btn btn-success mx-2 my-1">Cloturer la journee</a>
	<a href="{{route('todos.index')}}" class="btn btn-default">Acceuil</a>
</div>

@foreach($todos as $todo)
	@include("pages.todos.info")
@endforeach

{{$todos->links("vendor.pagination.bootstrap-4")}}
@endsection

resources/views/pages/mail.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<style>
@media  only screen and (max-width: 600px) {
.inner-body {
width: 100% !important;
}

.footer {
width: 100% !important;
}
}

@media  only screen and (max-width: 500px) {
.button {
width: 100% !important;
}
}
</style>
</head>
<body style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; -webkit-text-size-adjust: none; background-color: #ffffff; color: #718096; height: 100%; line-height: 1.4; margin: 0; padding: 0; width: 100% !important;">

<table class="wrapper" width="100%" cellpadding="0" cellspacing="0" role="presentation" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%; background-color: #edf2f7; margin: 0; padding: 0; width: 100%;">
<tr>
<td align="center" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative;">
<table class="content" width="100%" cellpadding="0" cellspacing="0" role="presentation" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%; margin: 0; padding: 0; width: 100%;">
<tr>
<td class="header" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; padding: 25px 0; text-align: center;">
<a href="http://localhost:8000/todos" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; color: #3d4852; font-size: 19px; font-weight: bold; text-decoration: none; display: inline-block;">
Laravel-todo
</a>
</td>
</tr>

<!-- Email Body -->
<tr>
<td class="body" width="100%" cellpadding="0" cellspacing="0" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%; background-color: #edf2f7; border-bottom: 1px solid #edf2f7; border-top: 1px solid #edf2f7; margin: 0; padding: 0; width: 100%;">
<table class="inner-body" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 570px; background-color: #ffffff; border-color: #e8e5ef; border-radius: 2px; border-width: 1px; box-shadow: 0 2px 0 rgba(0, 0, 150, 0.025), 2px 4px 0 rgba(0, 0, 150, 0.015); margin: 0 auto; padding: 0; width: 570px;">
<!-- Body content -->
<tr>
<td class="content-cell" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; max-width: 100vw; padding: 32px;">
<h1 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; color: #3d4852; font-size: 18px; font-weight: bold; margin-top: 0; text-align: left;">Hello!</h1>
<p style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;">The todo #34 has been affected to you by valere</p>
<table class="action" align="center" width="100%" cellpadding="0" cellspacing="0" role="presentation" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%; margin: 30px auto; padding: 0; text-align: center; width: 100%;">
<tr>
<td align="center" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative;">
<table width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative;">
<tr>
<td align="center" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative;">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative;">
<tr>
<td style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative;">
<a href="http://localhost:8000/todos" class="button button-primary" target="_blank" rel="noopener" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; -webkit-text-size-adjust: none; border-radius: 4px; color: #fff; display: inline-block; overflow: hidden; text-decoration: none; background-color: #2d3748; border-bottom: 8px solid #2d3748; border-left: 18px solid #2d3748; border-right: 18px solid #2d3748; border-top: 8px solid #2d3748;">See all todos</a>
</td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>
</table>
<p style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;">Thank you for using our application!</p>
<p style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;">Regards,<br>
Laravel-todo</p>


<table class="subcopy" width="100%" cellpadding="0" cellspacing="0" role="presentation" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; border-top: 1px solid #e8e5ef; margin-top: 25px; padding-top: 25px;">
<tr>
<td style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative;">
<p style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; line-height: 1.5em; margin-top: 0; text-align: left; font-size: 14px;">If you’re having trouble clicking the "See all todos" button, copy and paste the URL below
into your web browser: <span class="break-all" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; word-break: break-all;"><a href="http://localhost:8000/todos" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; color: #3869d4;">http://localhost:8000/todos</a></span></p>

</td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>

<tr>
<td style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative;">
<table class="footer" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 570px; margin: 0 auto; padding: 0; text-align: center; width: 570px;">
<tr>
<td class="content-cell" align="center" style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; max-width: 100vw; padding: 32px;">
<p style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; position: relative; line-height: 1.5em; margin-top: 0; color: #b0adc5; font-size: 12px; text-align: center;">© 2021 Laravel-todo. All rights reserved.</p>

</td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>